server:
  port: 5555
spring:
  application:
    name: aries-zuul
eureka:
  instance:
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 15
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
zuul:
  routes:
    leo:
      path: /sample/**
      serviceId: aries-sample-provider
