server:
  port: 8081
spring:
  application:
    name: aries-sample-provider
  datasource:
    platform: h2
  jpa:
    showSql: true
logging:
  level:
    root: info
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
ufrog:
  app:
    enabled: true
  client:
    resultCodeClass: net.ufrog.aries.sample.client.contracts.ResultCode