server:
  port: ${config.port:8761}
spring:
  application:
    name: aries-eureka
eureka:
#  server:
#    responseCacheUpdateIntervalMs: 3000
#    responseCacheAutoExpirationInSeconds: 180
#    evictionIntervalTimerInMs: 3000
#    enableSelfPreservation: true
  instance:
#    appname: aries-eureka
    hostname: 127.0.0.1
#    leaseExpirationDurationInSeconds: 15
#    leaseRenewalIntervalInSeconds: 5
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
