server:
  port: 8888
spring:
  application:
    name: aries-config
  cloud:
    config:
      uri: http://127.0.0.1:8888
      server:
        git:
          uri: https://git.coding.net/ufrog/ufrog-aries.git
          username: ufrog.net@gmail.com
          password: frog1984
          search-paths: aries-config/src/main/resources/repo