spring:
  application:
    name: aries-config
  cloud:
    config:
      server:
        git:
          uri: https://git.coding.net/ufrog/lc-config.git
          username: ufrog.net@gmail.com
          password: frog1984
          search-paths: ufrog-aries,ufrog-leo,ufrog-pisces,lc-thor,lc-avenger