server:
  port: ${config.port:8080}
spring:
  application:
    name: aries-config
  cloud:
    config:
      server:
        git:
          uri: ${config.git.uri}
          username: ${config.git.username}
          password: ${config.git.password}
          search-paths: ${config.git.paths}