server:
  port: 5566
spring:
  application:
    name: aries-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: aries-sample-provider
        uri: lb://aries-sample-provider
        predicates:
        - Path=/aries/{segment}
        filters:
        - SetPath=/sample/{segment}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000