server:
  port: 5566
spring:
  application:
    name: aries-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: leo-server-sso
        uri: lb://leo-server
        predicates:
        - Path=/sso/**
        filters:
        - StripPrefix=1
        - PrefixPath=/api
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/