server:
  port: 8082
spring:
  application:
    name: aries-sample-consumer
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
ufrog:
  app:
    enabled: true
    config:
      client:
        resultCodeClass: net.ufrog.aries.sample.client.contract.ResultCode