server:
  port: 8081
spring:
  application:
    name: aries-sample-provider
  datasource:
    platform: h2
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
ufrog:
  app:
    enabled: true
    config:
      client:
        resultCodeClass: net.ufrog.aries.sample.client.contract.ResultCode