spring:
  application:
    name: leo-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.111.4.49/ufrog_leo_dev?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: dev
    password: mMZc%j13l
  jpa:
    database: mysql
    show-sql: true
  jetbrick:
    template:
      enabled: true
      charset: utf-8
      content-type: text/html
      prefix: templates/default/
      suffix: .html
      config:
        jetx.import.classes: net.ufrog.common.app.App, net.ufrog.common.spring.app.SpringWebApp, net.ufrog.leo.domains.models.*, net.ufrog.leo.beans.**
        jetx.trim.directive.comments: "true"
        jetx.template.loaders: $loader
        $loader: jetbrick.template.loader.ClasspathResourceLoader
        $loader.reloadable: "true"
logging:
  level:
    root: info
#    org.hibernate: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
#    com.itmuch.youran.persistence: error
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
ufrog:
  app:
    enabled: true
    config:
      app:
        secret: zbh7DN0sLZYI5d6L0NzCwklr0NtZExi3RJ6ERKrjIzYuGz6WZYjplu2J0tKqEA8T
        messages: classpath:messages-domain,classpath:messages-service,classpath:messages
      pattern:
        uuid: "[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"
        cellphone: "1[3578][0-9]{9}"
        email: "[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[a-zA-Z0-9](?:[\\w-]*[\\w])?"
      path:
        resource:
          common: //10.111.4.49:800/leo/resources
          host: //10.111.4.49:800/leo/resources/leo
      cache:
        default:
          duration: 4h
          prefix: leo_
#        redis:
#          duration: 4h
#          prefix: leo_
#          type: net.ufrog.common.redis.JedisClusterCacheImpl
#          server: 43.254.106.50:7001,43.254.106.50:7002
#          serializer: net.ufrog.common.redis.serializers.ByteArraySerializer
#      thread:
#        default:
#          type: single
      leo:
        accessTokenManager: net.ufrog.leo.server.accesstoken.MemAccessTokenManager